export const theme = {
  colors: {
    primary: "#2E7D5E",
    primaryLight: "#52B788",
    primaryPastel: "#B7E4C7",
    primaryUltraLight: "#D8F3DC",
    background: "#F8FAF9",
    cardBackground: "#FFFFFF",
    textPrimary: "#1B2D27",
    textSecondary: "#6B8F71",
    textMuted: "#9DB5A0",
    border: "#D8EDE0",
    error: "#E76F51",
    errorLight: "#FDE8E4",
    warning: "#F4A261",
    warningLight: "#FEF0E6",
    success: "#2E7D5E",
    successLight: "#D8F3DC",
    white: "#FFFFFF",
    shadow: "rgba(46, 125, 94, 0.12)",
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 16,
    lg: 24,
    xl: 32,
  },
  borderRadius: {
    sm: 8,
    md: 12,
    lg: 16,
    xl: 24,
    full: 999,
  },
  fontSize: {
    xs: 11,
    sm: 13,
    md: 15,
    lg: 17,
    xl: 20,
    xxl: 24,
    xxxl: 32,
  },
  shadow: {
    small: {
      shadowColor: "#2E7D5E",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.08,
      shadowRadius: 8,
      elevation: 3,
    },
    medium: {
      shadowColor: "#2E7D5E",
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.12,
      shadowRadius: 16,
      elevation: 6,
    },
  },
};
